version: 0.1

phases:
 pre_build:
   commands: 
     - echo Logging into github repo...
     - git clone https://github.com/MrAnkit07/docker_ecs.git
     - echo "Logging in to Amazon ECR..."
     #-$nginx_ecr_cred
     - aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com

 build: 
   commands: 
     - echo project building on `date`
     - echo building docker image.....
     - docker build -t nginx_ecs_cicd . 
     - docker tag nginx_ecs_cicd:latest 422040052713.dkr.ecr.ap-south-1.amazonaws.com/nginx_ecs_cicd:latest
 post_build: 
   commands:
     - echo build completed on `date`
     - echo pushing build artifact in ECR....
     - docker push $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$ECRNAME:latest 


