version: 0.1

phases:
 pre_build:
   commands: 
     - echo Logging into github repo...
     - git clone https://github.com/MrAnkit07/docker_ecs.git

 build: 
   commands: 
     - echo project building on `date`
     - echo building docker image.....
     - docker build -t ws .
     - docker tag ws public.ecr.aws/n7y7m9h7/nginx_ecs_cicd
 post_build: 
   commands:
     - echo build completed on `date`
     - echo pushing build artifact in ECR....
     - docker push public.ecr.aws/n7y7m9h7/nginx_ecs_cicd 


